services: 
  olimpo:
    image: luispmv/olimpo-api:latest
  webserver:
    image: nginx
    ports:
      - "8000:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - olimpo

